
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientWrapper from "@/components/ClientWrapper";
import "./globals.css";


export const metadata: Metadata = {
  title: "srummanf's vetrina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans bg-gradient-to-tr from-zinc-950 via-[#242a2b] to-neutral-950 overflow-x-hidden min-w-screen flex min-h-screen flex-col items-center justify-between`}
      >
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}